"use client";
import {FormEvent,useState}from"react";import{useRouter}from"next/navigation";
type Block={id:string;type:string;data:any};type Lesson={id:string;title:string;blocks:Block[]};type Module={id:string;title:string;lessons:Lesson[]};
export function CourseBuilder({courseId,modules,status}:{courseId:string;modules:Module[];status:string}){const router=useRouter();const[busy,setBusy]=useState(false);const[error,setError]=useState("");
async function post(url:string,data?:unknown){setBusy(true);setError("");const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:data?JSON.stringify(data):undefined});const j=await r.json();setBusy(false);if(!r.ok){setError(j.error==="COURSE_INCOMPLETE"?"Add at least one lesson to every module before publishing.":j.error??"Something went wrong.");return false}router.refresh();return true}
async function addModule(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(await post("/api/v1/creator/courses/"+courseId+"/modules",{title:f.get("title")}))e.currentTarget.reset()}
async function addLesson(e:FormEvent<HTMLFormElement>,moduleId:string){e.preventDefault();const f=new FormData(e.currentTarget);if(await post("/api/v1/creator/modules/"+moduleId+"/lessons",{title:f.get("title")}))e.currentTarget.reset()}
async function addText(e:FormEvent<HTMLFormElement>,lessonId:string){e.preventDefault();const f=new FormData(e.currentTarget);if(await post("/api/v1/creator/lessons/"+lessonId+"/blocks",{type:"TEXT",data:{text:f.get("text")}}))e.currentTarget.reset()}
return <div className="builder"><div className="builderTop"><div><span className="courseBadge">{status}</span><h2>Course curriculum</h2></div><button disabled={busy||status==="PUBLISHED"} onClick={()=>post("/api/v1/creator/courses/"+courseId+"/publish")}>{status==="PUBLISHED"?"Published":"Publish course"}</button></div>{error?<p className="formError">{error}</p>:null}<div className="moduleList">{modules.map((m,i)=><section className="moduleCard" key={m.id}><div className="moduleTitle"><span>{String(i+1).padStart(2,"0")}</span><h3>{m.title}</h3></div>{m.lessons.map((l,j)=><article className="lessonEditor" key={l.id}><div><small>Lesson {j+1}</small><h4>{l.title}</h4></div><div className="blockList">{l.blocks.map(b=><div className="blockItem" key={b.id}><strong>{b.type}</strong><span>{b.type==="TEXT"?String(b.data?.text??"").slice(0,100):"Interactive content block"}</span></div>)}</div><form className="inlineBuilder" onSubmit={e=>addText(e,l.id)}><textarea name="text" required placeholder="Write a teaching paragraph, explanation or instruction..."/><button disabled={busy}>+ Text block</button></form></article>)}<form className="inlineBuilder compact" onSubmit={e=>addLesson(e,m.id)}><input name="title" required placeholder="New lesson title"/><button disabled={busy}>Add lesson</button></form></section>)}</div><form className="addModule" onSubmit={addModule}><input name="title" required placeholder="Module title — e.g. Understanding Solar PV Basics"/><button disabled={busy}>+ Add module</button></form></div>}
